<table border="1">
    <tr>
        <th id="nome">Destinatarios</th>
        <th id="data">Data</th>
        <th id="assunto">Assunto</th>

        <th id="visualizar">Visualizar</th>

        <th id="remover">Excluir</th>
    </tr>



    <?php
    foreach ($this->paginator as $saida):
    ?>
        <tr> 
           <?php
                $destinatarios="";
                foreach ($this->vDestinatarios as $dest):
                    if($dest->idmensagem==$saida->idmensagem){
                        $destinatarios=$destinatarios.$dest->nomedestinatario.", ";
                    }
                endforeach; ?>
            <td> 
                <?php
                     for ($x=0; $x<strlen($destinatarios)-2; $x++){
                         echo ($destinatarios[$x]);
                     }
                     if ($x!=0)
                         echo ('.');
                 ?>
            </td>
            <td><?= $saida->datahora ?></td>
            <td><?= $saida->assunto ?></td>

            <td>
                <a href="
                <?php
                echo $this->url(array('controller' => 'mensagens',
                    'action' => 'visualizar',
                    'id' => $saida->idmensagem
                        )
                );
                ?>" 
                   title="Visualizar"><img src="/imagens/search_lense.png"/>
                </a>
            </td>

            <td>
                <a href="
                <?php
                echo $this->url(array('controller' => 'mensagens',
                    'action' => 'remover',
                    'id' => $saida->idmensagem
                        )
                );
                ?>" 
                   title="Remover"><img src="/imagens/delete_2.png"/>
                </a>
            </td>

        </tr>
        <?php
        
    endforeach;
    ?>
</table>

<div id="paginacao">
    <?= $this->paginationControl($this->p, 'Sliding', 'my_pagination_control.phtml'); ?>
</div>

<div id="botaoCad">
    <a href="<?php echo $this->url(array('controller' => 'mensagens', 'action' => 'novo')); ?>" 
       title="Enviar">Enviar Mensagem</a>
</div>
