<?php echo $this->headLink()->appendStylesheet('/css/telaMensagens.css');
      echo $this->headScript()->appendFile('/js/jquery-1.7.2.js');
      echo $this->headScript()->appendFile('/js/layoutTabela.js');
?>


<div id="confMsg">
    <ul >
        <li><a href="<?php
                    echo $this->url(array('controller' => 'mensagens',
                        'action' => 'listar',
                            )
                    );
                    ?>">Caixa de Entrada</a></li>
        <li><a href="<?php
                    echo $this->url(array('controller' => 'mensagens',
                        'action' => 'novo',
                            )
                    );
                    ?>">Nova Mensagem</a></li>
        <li><a href="<?php
                    echo $this->url(array('controller' => 'mensagens',
                        'action' => 'caixa-saida',
                            )
                    );
                    ?>">Caixa de saída</a></li>

    </ul>
</div>

<fieldset>
    <legend>Caixa de Saída</legend> 
    <?php
    foreach ($this->paginator as $saida):
    ?>
        <ul id="email"> 
           <?php
                $destinatarios="";
                foreach ($this->vDestinatarios as $dest):
                    if($dest->idmensagem==$saida->idmensagem){
                        $destinatarios=$destinatarios.$dest->nomedestinatario.", ";
                    }
                endforeach; ?>
            <li> Para: 
               
                <?php
                     for ($x=0; $x<strlen($destinatarios)-2; $x++){
                         echo ($destinatarios[$x]);
                     }
                     if ($x!=0)
                         echo ('.');
                 ?>
            </li>
            <li> - <?= $saida->assunto ?></li>
            <li> - <?= $saida->datahora ?></li>

            <li id="remover">
                <a href="
                <?php
                echo $this->url(array('controller' => 'mensagens',
                    'action' => 'remover-saida',
                    'id' => $saida->idmensagem
                        )
                );
                ?>" 
                   title="Remover"><img src="/imagens/email-delete-icon.png"/>
                </a>
            </li>
            
            <li id="visualizar">
                <a href="
                <?php
                echo $this->url(array('controller' => 'mensagens',
                    'action' => 'visualizar-saida',
                    'id' => $saida->idmensagem
                        )
                );
                ?>" 
                   title="Visualizar"><img src="/imagens/search_lense.png"/>
                </a>
            </li>

       </ul>
        <?php
        
    endforeach;
    ?>
<div id="paginacao">
    <?= $this->paginationControl($this->p, 'Sliding', 'my_pagination_control.phtml'); ?>
</div>
</fieldset>



