<?php echo $this->headLink()->appendStylesheet('/css/telaMensagens.css');
      echo $this->headScript()->appendFile('/js/jquery-1.7.2.js');
      echo $this->headScript()->appendFile('/js/layoutTabela.js');
?>


<div id="confMsg">
    <ul>
        <li><a href="<?php
                    echo $this->url(array('controller' => 'mensagens',
                        'action' => 'listar',
                            )
                    );
                    ?>">Caixa de Entrada</a></li>
        <li><a href="<?php
                    echo $this->url(array('controller' => 'mensagens',
                        'action' => 'novo',
                            )
                    );
                    ?>">Nova Mensagem</a></li>
        <li><a href="<?php
                    echo $this->url(array('controller' => 'mensagens',
                        'action' => 'caixa-saida',
                            )
                    );
                    ?>">Caixa de saída</a></li>
    </ul>
</div>

<fieldset>
    <legend>Caixa de Entrada</legend> 
    <?php
        foreach ($this->paginator as $destinatario):
        if ($destinatario->lida == 't') $lida='Lida'; else $lida='Nao'; ?>

    
    <ul <?php if ($lida=='Lida') echo ('id="email"'); else echo('id="nlida"');?>>
            <li><?= $destinatario->nomeremetente ?> - </li>
            <li><?= $destinatario->assunto ?> - </li>
            <li><?= $destinatario->datahora ?> </li>
           
            <li id="remover">
                <a href="
                    <?php
                    echo $this->url(array('controller' => 'mensagens',
                        'action' => 'remover',
                        'id' => $destinatario->idmensagem
                            )
                    );
                    ?>" 
                   title="Remover"><img src="/imagens/delete_2.png"/>
                </a>
            </li>
            <li id="visualizar">
                <a href="
                    <?php
                    echo $this->url(array('controller' => 'mensagens',
                        'action' => 'visualizar',
                        'id' => $destinatario->idmensagem
                            )
                    );
                    ?>" 
                   title="Visualizar"><img src="/imagens/search_lense.png"/>
                </a></li>
                
        </ul>
        <?php
        
    endforeach;
    ?>
<div id="paginacao">
    <?= $this->paginationControl($this->p, 'Sliding', 'my_pagination_control.phtml'); ?>
</div>
 </fieldset>     
