<?php echo $this->headLink()->appendStylesheet('/css/telaAdm.css');?>

<div id="projetos">
        <ul>
            <fieldset>
                <legend>Últimos Projetos</legend>
                <?php 
                foreach ($this->paginator as $usuarioProjeto):
                ?>
                <li><p><?=$usuarioProjeto->nomeprojeto ?></p>
                        <p>Descrição da Projeto: <?=$usuarioProjeto->descricao ?></p>
                        <a href="
                            <?php 
                            echo $this->url(array('controller' => 'projetos', 
                                                'action'     => 'detalhar-projeto', 
                                                'idprojeto' => $usuarioProjeto->idprojeto
                                    )
                                    ); 
                            ?>">+ detalhes</a>
                </li> 
                <?php 
                    endforeach;
                ?>
        </fieldset></ul>

</div>

<div id="mensagens">
    <fieldset>
        <legend>Mensagens</legend>
            <?php 
            $contMsg=0;
            foreach($this->vMsgRecebida as $dest):
               $contMsg++;
            endforeach;
            if ($contMsg==0){
            ?>
            <p>Nenhuma mensagem não lida</p>
            <?php
             } else if ($contMsg==1) { 
            ?>
            <p>1 mensagem não lida</p>
            <?php
             } else { 
            ?>
            <p><?=$contMsg?> mensagens não lidas</p>
            <?php } ?>
            <a href="mensagens/listar" id="image"><img src="/imagens/email-icon.png"/></a>
    </fieldset>
</div>


<div id="tarefas">
        <ul><fieldset>
                <legend>Últimas Tarefas</legend>
                <?php 
                foreach ($this->paginator2 as $usuarioTarefa):
                ?> 
                <li><p><?= $usuarioTarefa->nometarefa?> </p>
                        <p>Descrição da Tarefa: <?= $usuarioTarefa->descricao?></p>
                        <a href="
                            <?php 
                            echo $this->url(array('controller' => 'projetos', 
                                                'action'     => 'detalhar-tarefa', 
                                                'idprojeto' => $usuarioTarefa->idprojeto,
                                                'idtarefa' => $usuarioTarefa->idtarefa
                                    )
                                    ); 
                            ?>" 
                         title="Detalhar">+detalhes</a>

                
                </li>
                <?php 
                endforeach;
                ?> 
<!--                <?php foreach ($this->tarefas as $tarefa): ?>
                <li>
                    <p>Tarefa: <?= $tarefa->nometarefa ?></p>
                    <p>Descrição: </p>
                    <p>Projeto: <?= $tarefa->nomeprojeto ?></p>
                    <a href="
                        <?=
                        $this->url(array(
                            'controller' => 'projetos', 
                            'action'     => 'listar-tarefas',
                            'idprojeto' => $projeto->idprojeto
                            )
                        ); 
                        ?>">+ detalhes
                    </a>
                </li>
                <?php endforeach; ?>
        </fieldset>
        </ul>-->
</div>



