<?php echo $this->headLink()->appendStylesheet('/css/telaAdm.css');?>

<div id="projetos">
        <ul><fieldset>
                <legend>Últimos Projetos</legend>
                <?php 
                foreach ($this->paginator as $usuarioProjeto):
                ?>
                <li><p><?=$usuarioProjeto->nomeprojeto ?></p>
                        <p>Descrição da Projeto: <?=$usuarioProjeto->descricao ?></p>
                        <a href="#">+ detalhes</a>
                </li> 
                <?php 
                    endforeach;
                ?>
        </fieldset></ul>
</div>


<div id="tarefas">
        <ul><fieldset>
                <legend>Últimas Tarefas</legend>
                <?php 
                foreach ($this->paginator2 as $usuarioTarefa):
                ?> 
                <li><p><?= $usuarioTarefa->nometarefa?> </p>
                        <p>Descrição da Tarefa: <?= $usuarioTarefa->descricao?></p>
                        <a href="#">+ detalhes</a>
                </li> 
                <?php 
                endforeach;
                ?> 
        </fieldset>
        </ul>
</div>

<div id="mensagens">
    <fieldset>
        <legend>Mensagens</legend>
            <p>Mensagens não lidas</p>
            <a href="#" id="image"><img src="/imagens/email-icon.png"/></a>
    </fieldset>
</div>