<?php
if ($this->mensagemErro): 
    echo $this->mensagemErro;
    echo '<br /><a href=" ' 
        . $this->url(array('controller' => 'usuarios', 'action' => 'listar')) 
        . '" title="Voltar">Voltar</a>';
else :
?>

<form action="editar" method="post">
    <input type="hidden" name="idUsuario" value="<?= $this->usuario->idusuario ?>" />
    <input type="hidden" name="idEndereco" value="<?= $this->usuario->endereco ?>" />
    <input type="hidden" name="idLogin" value="<?= $this->login->idlogin ?>" />
    <label>Nome: 
        <input type="text" id="nome" name="nome" value="<?= $this->usuario->nome ?>" />
    </label>
    <br /> 
    <label>Data Nascimento:
        <input type="text" id="dataNasc" name="dataNasc" value="<?= $this->usuario->datanasc ?>" />
    </label>
    <br /> 
    <label>Sexo: 
        <input type="text" id="sexo" name="sexo" value="<?= $this->usuario->sexo ?>" />
    </label>
    <br />
    <label>CPF: 
        <input type="text" id="cpf" name="cpf" value="<?= $this->usuario->cpf ?>" />
    </label>
    <br /> 
    <label>Telefone: 
        <input type="text" id="telefone" name="telefone" value="<?= $this->usuario->telefone ?>" />
    </label>
    <br /> 
    <label>E-mail: 
        <input type="text" id="email" name="email" value="<?= $this->usuario->email ?>" />
    </label>
    <br /> 
    <label>Login: 
        <input type="text" id="login" name="login" value="<?= $this->login->login ?>" />
    </label>
    <br /> 
    <label>Rua: 
        <input type="text" id="rua" name="rua" value="<?= $this->endereco->rua ?>" />
    </label>
    <br /> 
    <label>Numero: 
        <input type="text" id="num" name="num" value="<?= $this->endereco->num ?>" />
    </label>
    <br /> 
    <label>Bairro: 
        <input type="text" id="bairro" name="bairro" value="<?= $this->endereco->bairro ?>" />
    </label>
    <br />
    <label>Complemento: 
        <input type="text" id="complemento" name="complemento" value="<?= $this->endereco->complemento ?>" />
    </label>
    <br /> 
    <label>Cidade: 
        <input type="text" id="cidade" name="cidade" value="<?= $this->endereco->cidade ?>" />
    </label>
    <br /> 
    <label>Estado: 
        <input type="text" id="estado" name="estado" value="<?= $this->endereco->estado ?>" />
    </label>
    <br /> 

    <input type="submit" value="Atualizar" />
</form>

<?php
endif;
?>