<?php echo $this->headLink()->appendStylesheet('/css/telaUsuarios.css');
      echo $this->headScript()->appendFile('/js/jquery-1.7.2.js');
      echo $this->headScript()->appendFile('/js/layoutTabela.js');
?>

<div id="botaoCad">
    <a href="
    <?php 
    echo $this->url(array('controller' => 'usuarios', 'action' => 'novo')); 
    ?>" 
    title="Cadastrar">Cadastrar Usuário</a>
</div>

<table id="tabelaUsuarios" border="1">
        <tr>
        <th id="nome">Nome</th>
        <th id="email">Email</th>
        <th id="login1">Login</th>
        <th id="telefone">Telefone</th>
        <th id="visualizar">Visualizar</th>
        <th id="editar">Editar</th>
        <th id="remover">Excluir</th>
        </tr>
    <?php
    foreach ($this->paginator as $usuario):
    ?>
    <tr>
        <td><?= $usuario->nome ?></td>
        <td><?= $usuario->email ?></td>
        <td><?= $usuario->findParentLogin()->login ?></td>
        <td><?= $this->formataTelefone($usuario->telefone) ?></td>
        
        <td>
        <a href="
            <?php 
            echo $this->url(array('controller' => 'usuarios', 
                                  'action'     => 'visualizar',
                                  'id' => $usuario->idusuario
                    )
                    ); 
            ?>" 
            title="Visualizar"><img src="/imagens/Zoom-icon.png"/>
        </a>
        </td>
        <td>
        <a href="
            <?php 
            echo $this->url(array('controller' => 'usuarios', 
                                  'action'     => 'editar', 
                                  'id' => $usuario->idusuario
                    )
                    ); 
            ?>" 
            title="Editar"><img src="/imagens/31.png"/>
        </a>
        </td>
        <td>
        <a href="
            <?php 
            echo $this->url(array('controller' => 'usuarios', 
                                  'action'     => 'remover', 
                                  'id' => $usuario->idusuario
                    )
                    ); 
            ?>" 
            title="Remover"><img src="/imagens/118.png"/>
        </a>
        </td>
    </tr>
    <?php
    endforeach;
    ?>
</table>
<div id="paginacao">
    <?= $this->paginationControl($this->p, 'Sliding', 'my_pagination_control.phtml');?>
</div>
