<table border="1">
    <tr>
        <td>Nome</td>
        <td>Data Nascimento</td>
        <td>Sexo</td>
        <td>CPF</td>
        <td>Telefone</td>
        <td>E-mail</td>
        <td>Login</td>
        <td>Rua</td>
        <td>Num</td>
        <td>Bairro</td>
        <td>Complemento</td>
        <td>Cidade</td>
        <td>Estado</td>
    </tr>
    <?php
    foreach ($this->usuarios as $usuario):
    ?>
    <tr>
        <td><?= $usuario->nome ?></td>
        <td><?= $usuario->datanasc ?></td>
        <td><?= $usuario->sexo ?></td>
        <td><?= $usuario->cpf ?></td>
        <td><?= $usuario->telefone ?></td>
        <td><?= $usuario->email ?></td>
        <td><?= $usuario->findParentLogin()->login ?></td>
        <td><?= $usuario->findParentEnderecos()->rua ?></td>
        <td><?= $usuario->findParentEnderecos()->num ?></td>
        <td><?= $usuario->findParentEnderecos()->bairro ?></td>
        <td><?= $usuario->findParentEnderecos()->complemento ?></td>
        <td><?= $usuario->findParentEnderecos()->cidade ?></td>
        <td><?= $usuario->findParentEnderecos()->estado ?></td>
        
        <td>
        <a href="
            <?php 
            echo $this->url(array('controller' => 'usuarios', 
                                  'action'     => 'editar', 
                                  'id' => $usuario->idusuario
                    )
                    ); 
            ?>" 
            title="Editar">Editar
        </a>
        </td>
        <td>
        <a href="
            <?php 
            echo $this->url(array('controller' => 'usuarios', 
                                  'action'     => 'remover', 
                                  'id' => $usuario->idusuario
                    )
                    ); 
            ?>" 
            title="Remover">Remover
        </a>
        </td>
    </tr>
    <?php
    endforeach;
    ?>
</table>
<a href="
    <?php 
    echo $this->url(array('controller' => 'usuarios', 'action' => 'novo')); 
    ?>" 
    title="Novo usuário">Novo usuário
</a>