<?php echo $this->headLink()->appendStylesheet('/css/cadastroUsuarios.css');?>

<?php
if ($this->mensagemErro): 
    echo $this->mensagemErro;
    echo '<br /><a href=" ' 
        . $this->url(array('controller' => 'usuarios', 'action' => 'listar')) 
        . '" title="Voltar">Voltar</a>';
else :
?>

<div id="cadastro">
<form action="novo" method="post">
		<fieldset id="pessoal">
				<legend>Informa&ccedil;&otilde;es pessoais</legend>
		      
		      <label>Nome do Usu&aacute;rio: <br/>
		      <input type="text" size="60px"/></label><br/><br/>
		      
		      <label>Data de Nascimento:
		      <label style="margin-left: 3%">Sexo:<br/>
		      <input type="text" name="data_nasc" id="data_nasc" size="14"/></label>
		      
		      <select>
			  <option>Masculino</option>
			  <option>Feminino</option>
		      </select> </label><br/><br/>
		      
		      <label>CPF
		      <label style="margin-left: 33.5%">Telefone:<br/>
		      <input type="text"/></label>
		      <input type="text"/></label><br/><br/>
		      
		      <label>E-mail:<br/>
		      <input type="text" size="60px"/></label><br></br>


		      <label> Login do Usu&aacute;rio:<br/>
			  <input type="text"/></label>

		</fieldset>

		<fieldset id="endereco">
		      <legend>Endere&ccedil;o</legend>
		      
		      <label>Rua:
		      <label style="margin-left: 65%">N&uacute;mero:<br>
		      <input type="text" size="40px"/></label>
		      <input type="text" size="5px"/></label><br></br>
		      
		      <label>Bairro: 
		      <label style="margin-left: 30.5%">Complemento<br>
		      <input type="text"/></label>
		      <input type="text"/> </label><br><br>
		      
		      <label>Cidade: 
		      <label style="margin-left: 29.5%">Estado:<br>
		      <input type="text"/></label>
		      
		      <select>
			  <option>AC</option>
			  <option>AL</option>
			  <option>AM</option>
			  <option>AP</option>
			  <option>BA</option>
			  <option>CE</option>
			  <option>ES</option>
			  <option>GO</option>
			  <option>MA</option>
			  <option>MG</option>
			  <option>MS</option>
			  <option>MT</option>
			  <option>PA</option>
			  <option>PB</option>
			  <option>PE</option>
			  <option>PI</option>
			  <option>PR</option>
			  <option>AC</option>
			  <option>RJ</option>
			  <option>RN</option>
			  <option>RO</option>
			  <option>RR</option>
			  <option>RS</option>
			  <option>SC</option>
			  <option>SE</option>
			  <option>SP</option>
			  <option>TO</option>
		      </select></label> <br></br>


			<input id="cancelar" type="submit" value="Cancelar"/>
			<input id="salvar" type="submit" value="Salvar"/>
		    
		 </fieldset>
</form>
    </div>

<?php
endif;
?>