<?php echo $this->headLink()->appendStylesheet('/css/cadastroUsuarios.css');?>

<?php
if ($this->mensagemErro): 
    echo $this->mensagemErro;
    echo '<br /><a href=" ' 
        . $this->url(array('controller' => 'usuarios', 'action' => 'listar')) 
        . '" title="Voltar">Voltar</a>';
else :
?>

<div id="cadastro">

    <form action="novo" method="post">
        <fieldset id="pessoal">
            <legend>Informa&ccedil;&otilde;es pessoais</legend>

            <label>Nome do Usu&aacute;rio: <br/>
            <input type="text" id="nome" name="nome" size="60px"/></label><br/><br/>

            <label>Data de Nascimento:
            <label style="margin-left: 3%">Sexo:<br/>
            <input type="text" id="dataNasc" name="dataNasc" size="14"/></label>

            <select id="sexo" name="sexo"> 
            <option value="M">Masculino</option>
            <option value="F">Feminino</option>
            </select> </label><br/><br/>

            <label>CPF
            <label style="margin-left: 33.5%">Telefone:<br/>
            <input type="text" id="cpf" name="cpf"/></label>
            <input type="text"id="telefone" name="telefone"/></label><br/><br/>

            <label>E-mail:<br/>
            <input type="text" id="email" name="email" size="60px"/></label><br></br>


            <label> Login do Usu&aacute;rio:<br/>
            <input type="text" id="login" name="login"/></label>

        </fieldset>

        <fieldset id="endereco">
            <legend>Endere&ccedil;o</legend>

            <label>Rua:
            <label style="margin-left: 65%">N&uacute;mero:<br>
            <input type="text" id="rua" name="rua" size="40px"/></label>
            <input type="text" id="num" name="num" size="5px"/></label><br></br>

            <label>Bairro: 
            <label style="margin-left: 30.5%">Complemento<br>
            <input type="text" id="bairro" name="bairro"/></label>
            <input type="text" id="complemento" name="complemento"/> </label><br><br>

            <label>Cidade: 
            <label style="margin-left: 29.5%">Estado:<br>
            <input type="text" id="cidade" name="cidade"/></label>

            <select id="estado" name="estado">
                <?php 
                foreach ($this->estados as $estado) 
                    echo "<option value\"$estado\">$estado</option>";
                ?>
            </select></label> <br></br>

            <input id="cancelar" type="reset" value="Cancelar"/>
            <input id="salvar" type="submit" value="Salvar"/>
            
        </fieldset>
    </form>
</div>

<?php
endif;
?>