<?php
if ($this->mensagemErro): 
    echo $this->mensagemErro;
    echo '<br /><a href=" ' 
        . $this->url(array('controller' => 'usuarios', 'action' => 'listar')) 
        . '" title="Voltar">Voltar</a>';
else :
?>

<form action="novo" method="post">
    <label>Nome: <input type="text" id="nome" name="nome" /></label><br />
    <label>Data Nascimento: <input type="text" id="dataNasc" name="dataNasc" /></label><br /> 
    <label>Sexo: <input type="text" id="sexo" name="sexo" /></label><br /> 
    <label>CPF: <input type="text" id="cpf" name="cpf" /></label><br /> 
    <label>Telefone: <input type="text" id="telefone" name="telefone" /></label><br /> 
    <label>E-mail: <input type="text" id="email" name="email" /></label><br /> 
    <label>Login: <input type="text" id="login" name="login" /></label><br />
    <label>Rua: <input type="text" id="rua" name="rua" /></label><br /> 
    <label>Numero: <input type="text" id="num" name="num" /></label><br /> 
    <label>Bairro: <input type="text" id="bairro" name="bairro" /></label><br /> 
    <label>Complemento: <input type="text" id="complemento" name="complemento" /></label><br /> 
    <label>Cidade: <input type="text" id="cidade" name="cidade" /></label><br /> 
    <label>Estado: <input type="text" id="estado" name="estado" /></label><br /> 

    <input type="submit" value="Cadastrar" />
</form>

<?php
endif;
?>