<?php
if ($this->mensagemErro)
    echo $this->mensagemErro;
?>

<form action="login" method="post">
    
    <label>Login:
        <br />
        <input type="text" name="login" size="40" placeholder="Digite seu login"/>
    </label>
    <br />
    <br />
    <label>Senha:
        <br />
        <input type="password" name="senha" size="40" placeholder="Digite sua senha" />
    </label>
    <br />
    <br />

    <input id="botao" type="submit" value="Entrar"/><br><br>
    <a id="senhaesq" href="/login/solicitar">Esqueceu sua senha?</a>
    
</form>