<?php echo $this->headLink()->appendStylesheet('/css/novaSenha.css');?>

<div id="geral">
    <form action="loginRed" method="post">
        <label>Nova Senha: <br />
            <input type="password" name="email" size="50" placeholder="Digite sua nova senha"/>
        </label>
        <br /> <br />
        
        <label><span>Confirmar Senha: </span><br />
            <input type="password" name="email" size="50" placeholder="Digite sua nova senha"/>
        </label>
        <br /> <br />

        <input id="botao" type="submit" value="OK"/><br/><br/>
    </form>
</div>