<?php 
if ($this->emailEnviado):
    echo '<p>Foi enviado um e-mail com informações de como realizar a alteração da senha.</p>';
    echo '<p>Verifique sua caixa de entrada.</p>';
else:
?>
<div id="geral">
    <form action="solicitar" method="post">
        <label>Email:
            <br />
            <input type="text" name="email" size="50" placeholder="Digite seu email"/>
        </label>
        <br /><br />
        <input id="botao" type="submit" value="OK"/>
        <br /><br />
    </form>
</div>
<?php endif; ?>