<?php echo $this->doctype('XHTML1_TRANSITIONAL'); ?>
<html>
  <head>
    <title>DarthSCM | </title>
    <link rel="stylesheet" type="text/css" href="/css/geral.css" />
    <link rel="icon" href="/imagens/favicon.ico" type="image/x-icon" sizes="16x16" />
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <?= $this->headLink(); ?>    
    <?= $this->headScript();?>
  </head>

    <body>
        <div id="header">
            <img src="/imagens/logo.png" width="145" height="75"/>
            <div id="loginX">
                    <a href="#"><?= $this->usuarioLogado->nome ?></a> | <a href="/login/logout">logout</a>
                    <br><a href="#"><img src="/imagens/Brazil-icon.png"/></a>
                    <a href="#"><img src="/imagens/France-icon.png"/></a>
                    <a href="#"><img src="/imagens/United-States-of-Americ-icon.png"/></a>
                    <a href="#"><img src="/imagens/Spain-icon.png"/></a>
            </div>
            
            <div id="acess">
                <a href="#"><img src="/imagens/contrast-high-icon.png"/></a>
                <a href="#"><img src="/imagens/contrast-increase-icon.png"/></a>
                <a href="#"><img src="/imagens/font-add-icon.png"/></a>
                <a href="#"><img src="/imagens/font-delete-icon.png"/></a>
            </div>



        <div id="menu">
                <ul>
                    <li><a href="/index">Home</a></li>
                    <li><a href="/usuarios/listar">Usu&aacute;rios</a>
                            <ul>
                                 <li><a href="/usuarios/listar">Listar</a>
                                 </li>
                                 <li><a href="/usuarios/novo">Cadastrar</a>
                                 </li>
                            </ul>
                    </li>
                    
                    <li><a href="/projetos/listar">Projetos</a>
                            <ul>
                                    <li><a href="/projetos/listar">Listar</a></li>
                                    <li><a href="/projetos/novo">Cadastrar</a></li>
                            </ul>
                    </li>
                    <li><a href="/projetos/grafico-rel-projeto">Relatórios</a>
                            <ul>
                                    <li><a href="/projetos/relatorio-projeto">Projeto</a></li>
                                    <li><a href="/projetos/relatorio-colaborador">Pessoal</a></li>
                            </ul>
                    </li>
                    <li><a href="/mensagens">Mensagens</a>
                            <ul>
                                    <li><a href="/mensagens/novo">Nova</a></li>
                                    <li><a href="/mensagens/listar">Entrada</a></li>
                                    <li><a href="/mensagens/caixa-saida">Saída</a></li>
                            </ul>
                    </li>
                    <li><a href="#">Suporte</a>
                            <ul>
                                    <li><a href="#">FAQs</a></li>
                                    <li><a href="#">Contato</a></li>
                                    <li><a href="#">Manual</a></li>
                            </ul>
                    </li>
                </ul>
        </div>


    <div id="conteudo">
        <?php echo $this->layout()->content; ?>
    </div>


    <div id="rodape">
            <img src="/imagens/logo2.png">
    </div> 
    
    </body>
</html>