<html>
  <head>
    <title>Administrador</title>
    <link rel="stylesheet" type="text/css" href="/css/geral.css"/>
    <link rel="icon" href="/imagens/favicon.ico" type="image/x-icon" sizes="16x16" />
    <meta charset="UTF-8" />
  </head>

    <body>
        <div id="header">
            <img src="/imagens/logo.png" width="145px" height="75px"/>
            <div id="login">
                    <a href="#">Rafaela Souza</a> | <a href="/login/logout">logout</a>
                    <br><a href="#"><img src="/imagens/Brazil-icon.png"/></a>
                    <a href="#"><img src="/imagens/France-icon.png"/></a>
                    <a href="#"><img src="/imagens/United-States-of-Americ-icon.png"/></a>
                    <a href="#"><img src="/imagens/Spain-icon.png"/></a>
            </div>
        </div>



        <div id="menu">
                <ul>
                    <li><a href="/index">Home</a></li>
                    <li><a href="/usuarios/listar">Usu&aacute;rios</a>
                            <ul>
                                 <li><a href="/usuarios/listar">Listar</a>
                                 </li>
                                 <li><a href="/usuarios/novo">Cadastrar</a>
                                 </li>
                            </ul>
                    </li>
                    
                    <li><a href="/projetos/listar">Projetos</a>
                            <ul>
                                    <li><a href="/projetos/listar">Listar</a></li>
                                    <li><a href="/projetos/novo">Cadastrar</a></li>
                            </ul>
                    </li>
                    <li><a href="/projetos/grafico-rel-projeto">Relatórios</a>
                            <ul>
                                    <li><a href="/projetos/relatorio-projeto">Projeto</a></li>
                                    <li><a href="/projetos/relatorio-colaborador">Pessoal</a></li>
                            </ul>
                    </li>
                    <li><a href="telaMensagens.html">Mensagens</a>
                            <ul>
                                    <li><a href="#nogo">Nova</a></li>
                                    <li><a href="#nogo">Entrada</a></li>
                            </ul>
                    </li>
                </ul>
        </div>


    <div id="conteudo">
        <?php echo $this->layout()->content; ?>
    </div>


    <div class="clear"></div>

    <div id="rodape">
            <img src="/imagens/logo2.png">
    </div>
    
    </body>
</html>