<html>
  <head>
    <title>DarthSCM | </title>
    <link rel="stylesheet" type="text/css" href="/css/loginRed.css" />
    <link rel="icon" href="/imagens/favicon.ico" type="image/x-icon" sizes="16x16" />
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  </head>

    <body>
            <img id="logo" src="/imagens/logo.png" width="440px" height="210px" />

            <div id="geral1">
                <?php echo $this->layout()->content; ?>
            </div>

                    <div id="rodape">
            <img src="/imagens/logo2.png" />
        </div>


    </body>
</html>