<html>
    <head>
        <title>Login</title>
        <link rel="stylesheet" type="text/css" href="css/login.css"/>
    </head>

    <body>
        <div id="container">
            <img id="logo" src="imagens/logo.png" width="500px" height="245px"/>

            <div id="geral">
                <?php echo $this->layout()->content; ?>
            </div>

        </div>

        <div id="rodape">
            <img src="imagens/logo2.png"/>
        </div>
    </body>
  
</html>