<?php
if ($this->mensagem): 
?>
<p><?=$this->mensagem?></p>
<a href='/projetos/alocar-colaborador/idprojeto/<?= $this->idProjeto ?>' title="Alocar outro colaborador">Alocar outro usuário</a>
<br />
<a href='/projetos/listar' title="Voltar">Voltar</a>
<?php
else: 
?>

<form action="alocar-colaborador" method="post">
    <label>Usuarios: 
        <select name="idusuario">
            <?php foreach ($this->vUsuarioProjeto as $usuarioProjeto):
                if ($usuarioProjeto->datafimusuario!=null && $usuarioProjeto->datafimusuario<=time('Y-m-d')){
            ?>
            <option value="<?= $usuarioProjeto->idusuario ?>"><?= $usuarioProjeto->nomeusuario ?></option>
            <?php 
            } 
            endforeach;
            foreach ($this->usuarios as $usuario):
            ?>
            <option value="<?= $usuario->idusuario ?>"><?= $usuario->nome ?></option>
            <?php endforeach; ?>
        </select>
    </label>
   <label>Papel: 
        <select name="papel">
            <option value="colaborador">Colaborador</option>
            <option value="gerente">Gerente</option>
        </select>
    </label>
    <input type="hidden" value="<?= $this->idProjeto ?>" name="idprojeto" />
    <input type="submit" value="Alocar" />
</form>
<?php
endif;
?>