<?php
if ($this->mensagemErro) { 
?>
<p><?=$this->mensagemErro?></p>
<a href='/projetos/listar-tarefas/idprojeto/<?= $this->tarefa->idprojeto ?>/idtarefa/<?= $this->tarefa->idtarefa ?>' title="Voltar">Voltar</a>
<?php
} else { ?>
<form action="desalocar-usuario-tarefa/idprojeto/<?= $this->tarefa->idprojeto ?>/idtarefa/<?= $this->tarefa->idtarefa ?>" method="post">
    <input type="hidden" name="idtarefa" value="<?= $this->tarefa->idtarefa ?>" />
    <input type="hidden" name="idprojeto" value="<?= $this->tarefa->idprojeto ?>" />
    <label>Nome do Usuario: 
        <select id="usuario" name="usuario">
            <?php 
            foreach($this->vRealiza as $usuarioTarefa)
                echo "<option value=\"$usuarioTarefa->idusuario\">$usuarioTarefa->nome</option>";
            ?>
        </select>     
    <input type="submit" value="Desalocar" />
</form>
<?php
} 
?>