<form action="desalocar-usuario-tarefa" method="post">
    <input type="hidden" name="idtarefa" value="<?= $this->tarefa->idtarefa ?>" />
    <input type="hidden" name="idprojeto" value="<?= $this->tarefa->idprojeto ?>" />
    <label>Nome do Usuario: 
        <select id="usuario" name="usuario">
            <?php 
            foreach($this->vRealiza as $usuarioTarefa)
                echo "<option value=\"$usuarioTarefa->idusuario\">$usuarioTarefa->nome</option>";
            ?>
        </select>     
    <input type="submit" value="Desalocar" />
</form>