<?php echo $this->headLink()->appendStylesheet('/css/detalharProjeto.css');?>

<fieldset id="projetos">
    <legend><?= $this->projeto->nome ?> </legend>
    <span> Número do projeto: </span> <b><?= $this->projeto->idprojeto ?> </b><br/>
    <span> Descrição: </span> <b><?= $this->projeto->descricao ?></b><br/>
    <? if ($this->projeto->datafim != null AND $this->projeto->datafim<=date('Y-m-d')) $estado='FECHADA'; else $estado='ABERTA'; ?>
    <span> Estado: </span> <b><?= $estado ?></b><br/>
    <span> Data de Inicio: </span> <b><?= $this->projeto->datainicio ?></b><br/>
    <span> Data de Fim (Previsão): </span> <b> <?= $this->projeto->dataprevfim ?></b><br/>
    <span> Data Final: </span> <b><?= $this->projeto->datafim ?></b><br/>
    <span> Todos os Gerentes: </span> <b>
        <ul>
            <?php
                $gerentes="";
                foreach ($this->vUsuarioProjeto as $vgerente):
                    if($vgerente->idprojeto==$this->projeto->idprojeto && $vgerente->papel=='gerente'){
                        $gerentes=$gerentes.$vgerente->nomeusuario.", ";
                    }
                endforeach; ?>
             <li> 
                <?php
                     for ($x=0; $x<strlen($gerentes)-2; $x++){
                         echo ($gerentes[$x]);
                     }
                     if ($x!=0)
                         echo ('.');
                 ?>
             </li>
        </ul></b> 
    <?php if ($estado=='ABERTA'){?>
    <span>Gerentes Atuais:</span>
        <b><ul>
            <?php
                $gerentes="";
                foreach ($this->vUsuarioProjeto as $vgerente):
                    if($vgerente->idprojeto==$this->projeto->idprojeto && $vgerente->papel=='gerente' && ($vgerente->datafimusuario==null OR $vgerente->datafimusuario>time('Y-m-d'))){
                        $gerentes=$gerentes.$vgerente->nomeusuario.", ";
                    }
                    endforeach; ?> 
                <li> 
                <?php
                    for ($x=0; $x<strlen($gerentes)-2; $x++){
                        echo ($gerentes[$x]);
                    }
                    if ($x!=0)
                        echo ('.');
                ?>
                </li>                
            </ul></b> 
    <?php 
        }?>
    <span> Todos os Colaboradores: </span>
        <b><ul>
                <?php
                    $colaboradores="";
                    foreach ($this->vUsuarioProjeto as $vgerente):
                        if($vgerente->idprojeto==$this->projeto->idprojeto && $vgerente->papel=='colaborador'){
                            $colaboradores=$colaboradores.$vgerente->nomeusuario.", ";
                        }
                    endforeach; ?>
                <li> 
                    <?php
                        for ($x=0; $x<strlen($colaboradores)-2; $x++){
                            echo ($colaboradores[$x]);
                        }
                        if ($x!=0)
                            echo ('.');
                    ?>
                </li>
            </ul></b> 
    <?php if ($estado=='ABERTA'){?>
    <span> Colaboradores Atuais: </span>
        <b><ul>
            <?php
                $colaboradores="";
                foreach ($this->vUsuarioProjeto as $vgerente):
                    if($vgerente->idprojeto==$this->projeto->idprojeto && $vgerente->papel=='colaborador' && ($vgerente->datafimusuario==null || $vgerente->datafimusuario>time('Y-m-d'))){
                        $colaboradores=$colaboradores.$vgerente->nomeusuario.", ";
                    }
                    endforeach; ?> 
                <li> 
                <?php
                    for ($x=0; $x<strlen($colaboradores)-2; $x++){
                        echo ($colaboradores[$x]);
                    }
                    if ($x!=0)
                        echo ('.');
                ?>
                </li>                
            </ul></b> <br/>
    <?php 
        }
    ?>
            <ul id="icones">         
                <li><a href="
                    <?php 
                    echo $this->url(array('controller' => 'projetos', 
                                        'action'     => 'editar', 
                                        'idprojeto' => $this->projeto->idprojeto
                            )
                            ); 
                    ?>" 
                    title="Editar"><img src="/imagens/pencil_edit.png"/>
                    </a></li>

                    <li><a href="
                    <?php 
                    echo $this->url(array('controller' => 'projetos', 
                                        'action'     => 'remover', 
                                        'idprojeto' => $this->projeto->idprojeto
                            )
                            ); 
                    ?>" 
                    title="Remover"><img src="/imagens/delete_2.png"/>
                    </a><li>

                    <li><a href="
                        <?php 
                        echo $this->url(array('controller' => 'projetos', 
                                            'action'     => 'fechar', 
                                            'idprojeto' => $this->projeto->idprojeto
                                )
                                ); 
                        ?>" 
                        title="Alocar"><img src="/imagens/check-64.png"/>
                    </a></li>

                    <li><a href="
                        <?php 
                        echo $this->url(array('controller' => 'projetos', 
                                            'action'     => 'alocar-colaborador', 
                                            'idprojeto' => $this->projeto->idprojeto
                                )
                                ); 
                        ?>" 
                        title="Desalocar"><img src="/imagens/alocar.png"/>
                    </a></li>

                    <li><a href="
                    <?php 
                    echo $this->url(array('controller' => 'projetos', 
                                        'action'     => 'desalocar-colaborador', 
                                        'idprojeto' => $this->projeto->idprojeto
                            )
                            ); 
                    ?>" 
                    title="Remover"><img src="/imagens/desalocar.png"/>
                    </a></li>

                    <li><a id="icone" href="
                        <?php 
                            echo $this->url(array('controller' => 'projetos', 
                                'action'     => 'relatorio-participacao', 
                                'idprojeto' => $this->projeto->idprojeto
                            )
                            ); 
                        ?>" 
                        title="Relatorio"><img src="/imagens/report.png"/>
                    </a> </li>
            </ul>
            
            

</fieldset>

    

<fieldset id="listaTarefas">
     <legend>Lista de Tarefas</legend>
        
    <div id="botaoCad">
        <a href="
        <?php 
        echo $this->url(array('controller' => 'projetos', 
                                'action'     => 'listar-tarefas',
                                'idprojeto' => $this->projeto->idprojeto
                )
                ); 
        ?>" 
        title="Editar">Detalhar Todas</a>
    </div><br/>

<?php
    foreach ($this->paginator as $tarefa):
?>
   <ul>  
        <li><span>Nome da Tarefa:</span> <b><?= $tarefa->nome ?></b><br/>
        <span>Descrição: </span> <b><?= $tarefa->descricao ?></b><br/>
        <a href="
            <?php 
                echo $this->url(array('controller' => 'projetos', 
                    'action'     => 'detalhar-tarefa', 
                    'idprojeto' => $tarefa->idprojeto, 
                    'idtarefa' => $tarefa->idtarefa
                )
                ); 
            ?>" >+ detalhes</a>
        </li>
   </ul>
    <?php
    endforeach;
    ?>
    
    <div id="paginacao">
    <?= $this->paginationControl($this->p, 'Sliding', 'my_pagination_control.phtml');?>
</div>

</fieldset>


