<?php echo $this->headLink()->appendStylesheet('/css/cadastroTarefas.css');?>

<form action='editar-tarefa/idprojeto/<?=$this->tarefa->idprojeto?>/idtarefa/<?=$this->tarefa->idtarefa?>/' method="post">
 <fieldset id="pessoal">
        <legend>Informa&ccedil;&otilde;es Gerais</legend>
    
<?php
    if ($this->mensagemErro) { 
?>

<p><?=$this->mensagemErro?></p>
<a href='/projetos/listar-tarefas/idprojeto/<?= $this->tarefa->idprojeto ?>' title="Voltar">Voltar</a>
<?php
} else { 
?>   
    <input type="hidden" name="idtarefa" value="<?= $this->tarefa->idtarefa ?>" />
    <input type="hidden" name="idprojeto" value="<?= $this->tarefa->idprojeto ?>" />
    
    <label>Nome: 
        <input type="text" id="nome" name="nome" size="60px" value="<?= $this->tarefa->nome ?>" />
    </label>
    <br /><br/>
    
     <label>Data Início: 
                <label style="margin-left: 19%">Data Fim(Previsão): <br/>
                    
                <input type="text" id="dataInicio" name="dataInicio" size="14px" value="<?= $this->tarefa->datainicio ?>"/></label>
                <input type="text" id="dataPrevFim" name="dataPrevFim" size="14px" value="<?= $this->tarefa->dataprevfim ?>"/></label><br /> <br/>  
    
    
    <label>Prioridade: <br/>
       <select type="text" id="prioridade" name="prioridade" />
            <option value="<?= $this->tarefa->prioridade ?>"><?= $this->tarefa->prioridade ?></option>
            <option>Maxima</option>
            <option>Alta</option>
            <option>Normal</option>
            <option>Baixa</option>
            <option>Minima</option>
        </select>
     
    </label>
    <br /> <br/>
    
    <label>Descricao: <br/>
         <textarea type="text" id="descricao" name="descricao" value="<?= $this->tarefa->descricao ?>" rows="5" cols="60"></textarea><br /><br /> 
    </label>
    <br /> <br/>
    
    <input id="salvar" type="submit" value="Atualizar" />
</form>
<?php
}
?>