<?php echo $this->headLink()->appendStylesheet('/css/cadastroProjeto.css');?>

<?php
if ($this->mensagemErro): 
    echo $this->mensagemErro;
    echo '<br /><a href=" ' 
        . $this->url(array('controller' => 'projetos', 'action' => 'listar')) 
        . '" title="Voltar">Voltar</a>';
else :
?>

<form action="novo" method="post">
    <fieldset id="pessoal">
        <legend>Informa&ccedil;&otilde;es Gerais</legend>
            <input type="hidden" name="idProjeto" value="<?= $this->projeto->idprojeto ?>" />
            <input type="hidden" name="idRepositorio" value="<?= $this->repositorio->idrepositorio ?>" />
    
            <label>Nome do Projeto: 
                <input type="text" id="nome" name="nome"size="60px" /><br/>
            </label><br /><br/>

    
    <label>Data Inicio: 
                <label id="dataFim">Data Final (Previs&atilde;o): <br/>
                <input type="text" id="dataInicio" name="dataInicio" size="14px" value="<?= $this->projeto->datainicio ?>"/></label>
     
                <input type="text" id="dataPrevFim" name="dataPrevFim" size="14px" value="<?= $this->projeto->dataprevfim ?>" /></label><br /> <br/>

     <label>Descrição: <br/>
        <textarea type="text" id="descricao" name="descricao" rows="5" cols="60  value="<?= $this->projeto->descricao ?>"> </textarea>
    </label>
    <br /> <br/>            
                
    <label>Repositório: <br/>
        <input type="text" id="repositorio" name="repositorio" value="<?= $this->repositorio->endereco ?>" />
    </label>
    <br /><br/>
    
    
    <input id="salvar" type="submit" value="Atualizar" />
    </fieldset>
</form>

<?php
endif;
?>