<table border="1">
    <tr>
        <td>Nome Usuario</td>
        <td>Nome Projeto</td>
        <td>Produtividade (tempo)</td>
    </tr>
    <?php
    foreach ($this->vRelatorioCol as $relatorio):
    ?>
    <tr>
        <td><?= $relatorio->nomeusuario ?></td>
        <td><?= $relatorio->nomeprojeto ?></td>
        <td><?= $relatorio->tempodedicado ?></td>     
    </tr>
    <?php
    endforeach;
    ?>
</table>
