<?php echo $this->headLink()->appendStylesheet('/css/telaTarefas.css');?>

<div type="button" id="botaoCad">
        <a href="    
            <?php 
                echo $this->url(array('controller' => 'projetos', 'action' => 'nova-tarefa'));
            ?>" 
        title="Novo projeto">Cadastrar</a>
</div>

<?php
    foreach ($this->paginator as $tarefa):
?>
<fieldset id="tarefas">
    <legend><?= $tarefa->nome ?> </legend>
    <span>Descri&ccedil;&atilde;o: </span><b><?= $tarefa->descricao ?></b> <br/>
    <? if ($tarefa->datafim != null AND $tarefa->datafim<=date('Y-m-d')) $estado='FECHADA'; else $estado='ABERTA'; ?>
    <span>Estado: </span> <b><?= $estado ?></b> <br/>
    <span>Data Início: </span> <b><?= $tarefa->datainicio ?></b> <span id="dataf">Data Fim (Previsão): </span> <b><?= $tarefa->dataprevfim ?></b> <br/>
    <span>Data Fim: </span> <b><?= $tarefa->datafim ?></b> <br/>
    <span>Colaboradores: </span>
    <b><ul>
                <?php
                    $colaboradores="";
                    foreach ($this->VTarefaUsuario as $realiza):
                        if($realiza->idtarefa==$tarefa->idtarefa){
                            $colaboradores=$colaboradores.$realiza->nomeusuario.", ";
                        }
                ?>
               <li>
                <?php
                endforeach; 
                 for ($x=0; $x<strlen($colaboradores)-2; $x++){
                     echo ($colaboradores[$x]);
                 }
                 if ($x!=0)
                     echo ('.');
                 ?>
                </li>
                
                  </ul>
    <?php if ($estado=='ABERTA'){?></b> <br/>
    <span>Colaboradores atuais: </span>  
    <b><ul>
                <?php
                    $colaboradores="";
                    foreach ($this->vRealiza as $realiza):
                        if($realiza->idtarefa==$tarefa->idtarefa){
                            $colaboradores=$colaboradores.$realiza->nome.", ";
                        }
                ?>
               <li>
                <?php
                    endforeach; 
                    for ($x=0; $x<strlen($colaboradores)-2; $x++){
                        echo ($colaboradores[$x]);
                    }
                    if ($x!=0)
                        echo ('.');
                 ?>
                </li>                
           </ul></b>
    <?php 
        }
        $subtarefas="";
        foreach ($this->SubTarefas as $subTar):
            if($subTar->idsupertarefa==$tarefa->idtarefa){
                $subtarefas=$subtarefas.$subTar->nome.", ";
            }
        endforeach; if ($subtarefas!=""){?></b> <br/>
    
    <span> Subtarefas: </span> 
    <b><ul>
        <li>
        <?php 
             for ($x=0; $x<strlen($subtarefas)-2; $x++){
                 echo ($subtarefas[$x]);
             }
             if ($x!=0)
                 echo ('.'); }
             ?>
        </li>
    </ul></b> <br/>
  

        <ul id="icones">          
                <li><a href="
                    <?php 
                    echo $this->url(array('controller' => 'projetos', 
                                        'action'     => 'editar-tarefa', 
                                        'idtarefa' => $tarefa->idtarefa,
                                        'idprojeto' => $tarefa->idprojeto
                            )
                            ); 
                    ?>" 
                title="Editar"><img src="/imagens/pencil_edit.png"/>
            </a></li>

            <li><a href="
                <?php 
                echo $this->url(array('controller' => 'projetos', 
                                    'action'     => 'remover-tarefa', 
                                    'idtarefa'   => $tarefa->idtarefa,
                                    'idprojeto'  => $tarefa->idprojeto
                        )
                        ); 
                ?>" 
                title="Remover"><img src="/imagens/delete_2.png"/>
            </a></li>

            <li><a href="
                <?php 
                echo $this->url(array('controller' => 'projetos', 
                                    'action'     => 'fechar-tarefa', 
                                    'idtarefa'   => $tarefa->idtarefa,
                                    'idprojeto'  => $tarefa->idprojeto
                        )
                        ); 
                ?>" 
                title="Fechar"><img src="/imagens/check-64.png"/>
            </a></li>

            <li><a href="
                <?php 
                echo $this->url(array('controller' => 'projetos', 
                                    'action'     => 'alocar-usuario-tarefa', 
                                    'idtarefa'   => $tarefa->idtarefa,
                                    'idprojeto'  => $tarefa->idprojeto
                        )
                        ); 
                ?>" 
                title="Alocar"><img src="/imagens/alocar.png"/>
            </a></li>

            <li><a href="
                <?php 
                echo $this->url(array('controller' => 'projetos', 
                                    'action'     => 'desalocar-usuario-tarefa', 
                                    'idtarefa'   => $tarefa->idtarefa,
                                    'idprojeto'  => $tarefa->idprojeto
                        )
                        ); 
                ?>" 
                title="Desalocar"><img src="/imagens/desalocar.png"/>
            </a></li>

            <li><a href="
                <?php 
                echo $this->url(array('controller' => 'projetos', 
                                    'action'     => 'adicionar-tempo', 
                                    'idtarefa'   => $tarefa->idtarefa,
                                    'idprojeto'  => $tarefa->idprojeto
                        )
                        ); 
                ?>" 
                title="Adicionar"><img src="/imagens/time_clock.png"/>
            </a></li>

            <li><a href="
                <?php 
                echo $this->url(array('controller' => 'projetos', 
                                    'action'     => 'nova-sub-tarefa', 
                                    'idtarefa'   => $tarefa->idtarefa,
                                    'idprojeto'  => $tarefa->idprojeto
                        )
                        ); 
                ?>" 
                title="NovaSubTarefa"><img src="/imagens/plus.png"/>
            </a></li>
       </ul>
       </fieldset>
    
    <?php
    endforeach;
    ?>

    
 <div id="paginacao">
    <?= $this->paginationControl($this->p, 'Sliding', 'my_pagination_control.phtml');?>
</div>
