<?php echo $this->headLink()->appendStylesheet('/css/telaProjetos.css');?>

<div type="button" id="botaoCad">
        <a href="    
            <?php 
                echo $this->url(array('controller' => 'projetos', 'action' => 'novo')); 
            ?>" 
        title="Novo projeto">Cadastrar</a>
</div>
    
<?php
    foreach ($this->projetos as $projeto):
?>

<div id="projetos">
<fieldset>
    <legend><?= $projeto->nomeprojeto ?> </legend>
    <p>Descri&ccedil;&atilde;o: <?= $projeto->descricao ?></p>
    <p>Data de Inicio: <?= $projeto->datainicioprojeto ?></p>
    <p>Data de Fim (Previs&atilde;o): <?= $projeto->dataprevfim ?></p>
    <p>Data Final: <?= $projeto->datafim ?></p>
    
           <a href="
            <?php 
            echo $this->url(array('controller' => 'projetos', 
                                  'action'     => 'detalhar-projeto', 
                                  'id' => $projeto->idprojeto
                    )
                    ); 
            ?>" 
            title="Detalhar"><img src="/imagens/delete-icon.png"/>
        </a>
    
        <a href="
            <?php 
            echo $this->url(array('controller' => 'projetos', 
                                  'action'     => 'editar', 
                                  'id' => $projeto->idprojeto
                    )
                    ); 
            ?>" 
            title="Editar"><img src="/imagens/edit.png"/>
        </a>
    
        <a href="
            <?php 
            echo $this->url(array('controller' => 'projetos', 
                                  'action'     => 'alocar', 
                                  'id' => $projeto->idprojeto
                    )
                    ); 
            ?>" 
            title="Remover"><img src="/imagens/alocar.png"/>
        </a>
        <a href="
            <?php 
            echo $this->url(array('controller' => 'projetos', 
                                  'action'     => 'desalocar', 
                                  'id' => $projeto->idprojeto
                    )
                    ); 
            ?>" 
            title="Remover"><img src="/imagens/edit.png"/>
        </a>
        </div>
        <br />
    <?php
    endforeach;
    ?>

</fieldset>

<br />
<!--        <td>
            <a href=" <?//= $projeto->findParentRepositorios()->endereco ?>">
            <?//= $projeto->findParentRepositorios()->endereco ?>
            </a>
        </td>
        <td><?//= $projeto->nomeusuario ?></td>
                
        <td>  -->
