<?php echo $this->headLink()->appendStylesheet('/css/telaProjetos.css');?>

<div type="button" id="botaoCad">
        <a href="    
            <?php 
                echo $this->url(array('controller' => 'projetos', 'action' => 'novo')); 
            ?>" 
        title="Novo projeto">Cadastrar Projeto</a>
</div>

    
<?php
    foreach ($this->paginator as $projeto):
?>

<fieldset id="projetos">
    <legend><?= $projeto->nomeprojeto ?> </legend>
    <p>Descri&ccedil;&atilde;o: <?= $projeto->descricao ?></p>
    <p>Data de Inicio: <?= $projeto->datainicioprojeto ?></p>
    <p>Data de Fim (Previs&atilde;o): <?= $projeto->dataprevfim ?></p>
    <p>Data Final: <?= $projeto->datafim ?></p>
    
    <ul id="icones">
            <li><a href="
            <?php 
            echo $this->url(array('controller' => 'projetos', 
                                  'action'     => 'detalhar-projeto', 
                                  'idprojeto' => $projeto->idprojeto
                    )
                    ); 
            ?>" 
            title="Remover"><img src="/imagens/desalocar.png"/>
            </a></li>
           <li><a href="
            <?php 
            echo $this->url(array('controller' => 'projetos', 
                                  'action'     => 'editar', 
                                  'idprojeto' => $projeto->idprojeto
                    )
                    ); 
            ?>" 
            title="Detalhar"><img src="/imagens/edit.png"/>
            </a></li>
    
            <li><a href="
            <?php 
            echo $this->url(array('controller' => 'projetos', 
                                  'action'     => 'remover', 
                                  'idprojeto' => $projeto->idprojeto
                    )
                    ); 
            ?>" 
            title="Editar"><img src="/imagens/delete-icon.png"/>
            </a><li>
    
            <li><a href="
                <?php 
                echo $this->url(array('controller' => 'projetos', 
                                    'action'     => 'fechar', 
                                    'idprojeto' => $projeto->idprojeto
                        )
                        ); 
                ?>" 
                title="Alocar"><img src="/imagens/fechar.png"/>
            </a></li>
            
            <li><a href="
                <?php 
                echo $this->url(array('controller' => 'projetos', 
                                    'action'     => 'alocar', 
                                    'idprojeto' => $projeto->idprojeto
                        )
                        ); 
                ?>" 
                title="Desalocar"><img src="/imagens/alocar.png"/>
            </a></li>
            
            <li><a href="
            <?php 
            echo $this->url(array('controller' => 'projetos', 
                                  'action'     => 'desalocar', 
                                  'idprojeto' => $projeto->idprojeto
                    )
                    ); 
            ?>" 
            title="Remover"><img src="/imagens/desalocar.png"/>
            </a></li>
            
        <br />
</fieldset>
   
        <?php
           // endforeach;
            endforeach;
        ?>
    
 <div id="paginacao">
    <?= $this->paginationControl($this->p, 'Sliding', 'my_pagination_control.phtml');?>
</div>

<br />
<!--        <td>
            <a href=" <?//= $projeto->findParentRepositorios()->endereco ?>">
            <?//= $projeto->findParentRepositorios()->endereco ?>
            </a>
        </td>
        <td><?//= $projeto->nomeusuario ?></td>
                
        <td>  -->
