<?php echo $this->headLink()->appendStylesheet('/css/telaTarefas.css');?>

<div type="button" id="botaoCad">
        <a href="    
            <?php 
                echo $this->url(array('controller' => 'projetos', 'action' => 'nova-tarefa'));
            ?>" 
        title="Novo projeto">Cadastrar</a>
</div>

<?php
    foreach ($this->tarefas as $tarefa):
?>

<div id="tarefas">
<fieldset>
    <legend><?= $tarefa->nome ?> </legend>
    <p>Descri&ccedil;&atilde;o: <?= $tarefa->descricao ?></p>
    <? if ($tarefa->datafim != null AND $tarefa->datafim<=date('Y-m-d')) $estado='FECHADA'; else $estado='ABERTA'; ?>
    <p>Estado: <?= $estado ?></p>
    <p>Data Início: <?= $tarefa->datainicio ?> Data Fim (Previsão): <?= $tarefa->dataprevfim ?></p>
    <p>Data Fim: <?= $tarefa->datafim ?>
    <p>Colaboradores:</p>
           <ul>
                <?php
                    $colaboradores="";
                    foreach ($this->VTarefaUsuario as $realiza):
                        if($realiza->idtarefa==$tarefa->idtarefa){
                            $colaboradores=$colaboradores.$realiza->nomeusuario.", ";
                        }
                ?>
               <li>
                <?php
                endforeach; 
                 for ($x=0; $x<strlen($colaboradores)-2; $x++){
                     echo ($colaboradores[$x]);
                 }
                 if ($x!=0)
                     echo ('.');
                 ?>
                </li>
                
                  </ul>
    <?php if ($estado=='ABERTA'){?>
    <p>Colaboradores atuais: </p> 
           <ul>
                <?php
                    $colaboradores="";
                    foreach ($this->vRealiza as $realiza):
                        if($realiza->idtarefa==$tarefa->idtarefa){
                            $colaboradores=$colaboradores.$realiza->nome.", ";
                        }
                ?>
               <li>
                <?php
                    endforeach; 
                    for ($x=0; $x<strlen($colaboradores)-2; $x++){
                        echo ($colaboradores[$x]);
                    }
                    if ($x!=0)
                        echo ('.');
                 ?>
                </li>                
           </ul>
    <?php 
        }
        $subtarefas="";
        foreach ($this->subtarefas as $subTar):
            if($subTar->idsupertarefa==$tarefa->idtarefa){
                $subtarefas=$subtarefas.$subTar->nome.", ";
            }
        endforeach; if ($subtarefas!=""){?>
    <p> Subtarefas: </p> 
    <ul>
        <li>
        <?php 
             for ($x=0; $x<strlen($subtarefas)-2; $x++){
                 echo ($subtarefas[$x]);
             }
             if ($x!=0)
                 echo ('.'); }
             ?>
        </li>
    </ul>

        <ul id="icones">          
                <li><a href="
                    <?php 
                    echo $this->url(array('controller' => 'projetos', 
                                        'action'     => 'editar-tarefa', 
                                        'idtarefa' => $tarefa->idtarefa,
                                        'idprojeto' => $tarefa->idprojeto
                            )
                            ); 
                    ?>" 
                title="Editar"><img src="/imagens/edit.png"/>
            </a></li>

            <li><a href="
                <?php 
                echo $this->url(array('controller' => 'projetos', 
                                    'action'     => 'remover-tarefa', 
                                    'idtarefa'   => $tarefa->idtarefa,
                                    'idprojeto'  => $tarefa->idprojeto
                        )
                        ); 
                ?>" 
                title="Remover"><img src="/imagens/edit.png"/>
            </a></li>

            <li><a href="
                <?php 
                echo $this->url(array('controller' => 'projetos', 
                                    'action'     => 'fechar-tarefa', 
                                    'idtarefa'   => $tarefa->idtarefa,
                                    'idprojeto'  => $tarefa->idprojeto
                        )
                        ); 
                ?>" 
                title="Fechar"><img src="/imagens/edit.png"/>
            </a></li>

            <li><a href="
                <?php 
                echo $this->url(array('controller' => 'projetos', 
                                    'action'     => 'alocar-usuario-tarefa', 
                                    'idtarefa'   => $tarefa->idtarefa,
                                    'idprojeto'  => $tarefa->idprojeto
                        )
                        ); 
                ?>" 
                title="Alocar"><img src="/imagens/edit.png"/>
            </a></li>

            <li><a href="
                <?php 
                echo $this->url(array('controller' => 'projetos', 
                                    'action'     => 'desalocar-usuario-tarefa', 
                                    'idtarefa'   => $tarefa->idtarefa,
                                    'idprojeto'  => $tarefa->idprojeto
                        )
                        ); 
                ?>" 
                title="Desalocar"><img src="/imagens/edit.png"/>
            </a></li>

            <li><a href="
                <?php 
                echo $this->url(array('controller' => 'projetos', 
                                    'action'     => 'adicionar-tempo', 
                                    'idtarefa'   => $tarefa->idtarefa,
                                    'idprojeto'  => $tarefa->idprojeto
                        )
                        ); 
                ?>" 
                title="Adiconar"><img src="/imagens/edit.png"/>
            </a></li>

            <li><a href="
                <?php 
                echo $this->url(array('controller' => 'projetos', 
                                    'action'     => 'nova-sub-tarefa', 
                                    'idtarefa'   => $tarefa->idtarefa,
                                    'idprojeto'  => $tarefa->idprojeto
                        )
                        ); 
                ?>" 
                title="NovaSubTarefa"><img src="/imagens/edit.png"/>
            </a></li>
       </ul>
       </fieldset>
    </div>
    <?php
    endforeach;
    ?>
