<form action="nova-tarefa" method="post">
    <label>Nome: <input type="text" id="nome" name="nome" /></label><br />
    <label>Data Início: <input type="text" id="dataInicio" name="dataInicio" /></label><br />
    <label>Data Fim(Previsão): <input type="text" id="dataPrevFim" name="dataPrevFim" /></label><br />     
    <label>Prioridade: <input type="text" id="prioridade" name="prioridade" /></label><br /> 
    <label>Descrição: <input type="text" id="descricao" name="descricao" /></label><br />      <label>Responsavel: 
        <select id="responsavel" name="responsavel">
            <?php 
            foreach($this->usuarios as $usuario)
                echo "<option value=\"$usuario->idusuario\">$usuario->nome</option>";
            ?>
        </select>
    </label>
    <br /> 
     
    <input type="submit" value="Cadastrar" />
</form>