<?php echo $this->headLink()->appendStylesheet('/css/cadastroTarefas.css');?>


<form action="nova-tarefa" method="post">
    <fieldset id="tarefa">
        <legend>Informações Gerais</legend>
            <input type="hidden" name="idprojeto" value="<?= $this->projeto->idprojeto ?>" />
            <label>Nome: <br/>
                <input type="text" id="nome" name="nome" size="60px" /></label><br /><br/>

            <label>Data Início: 
                <label style="margin-left: 19%">Data Fim(Previsão): <br/>
                    
                <input type="text" id="dataInicio" name="dataInicio" size="14px"/></label>
                <input type="text" id="dataPrevFim" name="dataPrevFim" size="14px"/></label><br /> <br/>  

            <label>Prioridade: 
            <label style="margin-left: 7%">Responsável: <br/>
                <select type="text" id="prioridade" name="prioridade" />
                    <option>Maxima</option>
                    <option>Alta</option>
                    <option>Normal</option>
                    <option>Baixa</option>
                    <option>Minima</option>
                </select>
            </label>

            <select id="responsavel" name="responsavel">
                <?php 
                foreach($this->usuarios as $usuario)
                    echo "<option value=\"$usuario->idusuario\">$usuario->nome</option>";
                ?>
            </select>
            
            </label><br/><br/>

            <label>Descrição: <br>
                <textarea type="text" id="descricao" name="descricao"  rows="5" cols="60"></textarea><br /><br /> 

           <input id="cancelar" type="reset" value="Cancelar"/>
            <input id="salvar" type="submit" value="Salvar"/>
             
    </fieldset>
</form>