<?php echo $this->headLink()->appendStylesheet('/css/cadastroProjeto.css');?>
<?php
if ($this->mensagemErro) { 
?>
<p><?=$this->mensagemErro?></p>
<a href='/projetos/listar' title="Voltar">Voltar</a>
<?php
} else { 
?>
<form action="novo" method="post">
    <fieldset id="pessoal">
        <legend>Informa&ccedil;&otilde;es Gerais</legend>
            
            <label>Nome do Projeto: 
                <input type="text" id="nome" name="nome"size="60px" /><br/></label><br />
            
            <label>Data Inicio: 
                <label id="dataFim">Data Final (Previs&atilde;o): <br/>
                <input type="text" id="dataInicio" name="dataInicio" size="14px" /></label>
     
                <input type="text" id="dataPrevFim" name="dataPrevFim" size="14px" /></label><br /> <br/>
                
            <label> Descri&ccedil;&atilde;o: <br/>
                <textarea id="descricao" rows="5" cols="60"></textarea></label><br></br>            
            
            <label>Repositório: 
            <label id="ger">Gerente: <br/>
                <input type="text" id="repositorio" name="repositorio" /></label> 
                <select id="gerente" name="gerente">
                    <?php 
                    foreach($this->usuarios as $usuario)
                        echo "<option value=\"$usuario->idusuario\">$usuario->nome</option>";
                    ?>
                </select><br/>
            </label>
    <br /> 
     
           <input id="cancelar" type="reset" value="Cancelar"/>
            <input id="salvar" type="submit" value="Salvar"/>
</form>

<?php } ?>

       