<form action="novo" method="post">
    <label>Nome: <input type="text" id="nome" name="nome" /></label><br />
    <label>Descrição: <input type="text" id="descricao" name="descricao" /></label><br /> 
    <label>Data Início: <input type="text" id="dataInicio" name="dataInicio" /></label><br />
    <label>Data Fim(Previsão): <input type="text" id="dataPrevFim" name="dataPrevFim" /></label><br /> 
    <label>Repositório: <input type="text" id="repositorio" name="repositorio" /></label><br /> 
    <label>Gerente: 
        <select id="gerente" name="gerente">
            <?php 
            foreach($this->usuarios as $usuario)
                echo "<option value=\"$usuario->idusuario\">$usuario->nome</option>";
            ?>
        </select>
    </label>
    <br /> 
     
    <input type="submit" value="Cadastrar" />
</form>