<table border="1">
    <tr>
        <td>Nome Projeto</td>
        <td>Produtividade (tempo)</td>
    </tr>
    <?php
    foreach ($this->vRelatorioProj as $relatorio):
        $tempo=$relatorio->tempodedicado;
        $int1=new DateInterval('P0D');
            $int2=new DateInterval('P0D');
            $d2="";$h2="";$m2="";
            projetos::trataInterval (&$tempo, &$int2);
            projetos::SomaInterval ($int1, $int2);
       ?>
    <tr>
        <td><?= $relatorio->nomeprojeto ?></td>
        <td><?= $int2->d." days ".$int2->format('%H').":".$int2->format('%I').":".$int2->format('%S')?></td>     
    </tr>
    <?php
    endforeach;
    ?>
</table>