<?php echo $this->headLink()->appendStylesheet('/css/telaGrafico.css');
      echo $this->headScript()->appendFile('/js/jquery-1.7.2.js');
      echo $this->headScript()->appendFile('/js/layoutTabela.js');
?>

<div type="button" id="botaoCad">
        <a href="#" title="Imprimir">Imprimir</a>
</div>

<table id="tabela">
    <tr>
        <th>Nome Projeto</th>
        <th>Produtividade (tempo)</th>
    </tr>
    <?php
    foreach ($this->vRelatorioProj as $relatorio):
        $tempo=$relatorio->tempodedicado;
        $int1=new DateInterval('P0D');
            $int2=new DateInterval('P0D');
            $d2="";$h2="";$m2="";
            projetos::trataInterval (&$tempo, &$int2);
            projetos::SomaInterval ($int1, $int2);
       ?>
    <tr>
        <td><?= $relatorio->nomeprojeto ?></td>
        <td><?= $int2->d." days ".$int2->format('%H').":".$int2->format('%I').":".$int2->format('%S')?></td>     
    </tr>
    <?php
    endforeach;
    ?>
</table>