<html>
  <head>
    <script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <script type="text/javascript">
      google.load("visualization", "1", {packages:["corechart"]});
      google.setOnLoadCallback(drawChart);
      function drawChart() {
        var data = google.visualization.arrayToDataTable([
          ['Projetos', 'Tempo de produtividade (dias)']
            <?php
            foreach ($this->vRelatorioProj as $relatorio):
                
               $tempo=$relatorio->tempodedicado;
                        $x=0; 
            $flagd=0; 
            $d2="";$h2="";$m2="";
            while ($x<strlen($tempo)-1){
                if ($tempo[$x]=='d'){
                   for ($y=0; $y<$x-1; $y++)
                       $d2=$d2.$tempo[$y];
                   $flagd=1;
                   break;
                }
                $x++;
            }
            if ($flagd==0)
                $x=0;
            while ($x<strlen($tempo)-1){
                if ($tempo[$x]==' '){ $x++;
                    while ($tempo[$x]!=':')
                    $h2=$h2.$tempo[$x++];
                   // if ($x==':'){
                    $x++;
                    while ($tempo[$x]!=':')
                        $m2=$m2.$tempo[$x++];
                        //if ($x==':')
                
                }
            $x++;
            }
            $int1=new DateInterval('P0D');
            $int2=new DateInterval('P0D');
            $int2->d=$d2;
            $int2->h=$h2;
            $int2->i=$m2;

        $min=$int2->i+$int1->i;
        $hora=$int2->h+$int1->h;
        $dia=$int2->d+$int1->d;
        if ($min>59){
            $hora=$hora+(int)$min/60;
            $min=$min%60;
        }
        $int2->i=$min;        
        if ($hora>23){
            $dia=$dia+(int)$hora/24;
            $hora=$hora%24;
        }
        $int2->h=$hora;
        $int2->d=$dia; ?>

            
          <?=",['".$relatorio->nomeprojeto."', ".$int2->d."]"?>
      <?php
    endforeach;
    ?>  
        ]);

        var options = {
          title: 'Tempo (em dias) de dedicação efetiva para cada projeto'
        };

        var chart = new google.visualization.PieChart(document.getElementById('chart_div'));
        chart.draw(data, options);
      }
    </script>
  </head>
  <body>
    <div id="chart_div" style="width: 900px; height: 500px;"></div>
    <table border="1">
    <tr>
        <td>Nome Projeto</td>
        <td>Produtividade (tempo)</td>
    </tr>
    <?php
    foreach ($this->vRelatorioProj as $relatorio):
    $tempo=$relatorio->tempodedicado;
            
            $x=0; 
            $flagd=0; 
            $d2="";$h2="";$m2="";
            while ($x<strlen($tempo)-1){
                if ($tempo[$x]=='d'){
                   for ($y=0; $y<$x-1; $y++)
                       $d2=$d2.$tempo[$y];
                   $flagd=1;
                   break;
                }
                $x++;
            }
            if ($flagd==0)
                $x=0;
            while ($x<strlen($tempo)-1){
                if ($tempo[$x]==' '){ $x++;
                    while ($tempo[$x]!=':')
                    $h2=$h2.$tempo[$x++];
                   // if ($x==':'){
                    $x++;
                    while ($tempo[$x]!=':')
                        $m2=$m2.$tempo[$x++];
                        //if ($x==':')
                
                }
            $x++;
            }
            $int1=new DateInterval('P0D');
            $int2=new DateInterval('P0D');
            $int2->d=$d2;
            $int2->h=$h2;
            $int2->i=$m2;

        $min=$int2->i+$int1->i;
        $hora=$int2->h+$int1->h;
        $dia=$int2->d+$int1->d;
        if ($min>59){
            $hora=$hora+(int)$min/60;
            $min=$min%60;
        }
        $int2->i=$min;        
        if ($hora>23){
            $dia=$dia+(int)$hora/24;
            $hora=$hora%24;
        }
        $int2->h=$hora;
        $int2->d=$dia; ?>
    <tr>
        <td><?= $relatorio->nomeprojeto ?></td>
        <td><?= $int2->d." days ".$int2->format('%H').":".$int2->format('%I').":".$int2->format('%S')?></td>     
    </tr>
    <?php
    endforeach;
    ?>
</table>
  </body>
</html>