<?php echo $this->headLink()->appendStylesheet('/css/telaGrafico.css');
      echo $this->headScript()->appendFile('/js/jquery-1.7.2.js');
      echo $this->headScript()->appendFile('/js/layoutTabela.js');
?>

<div type="button" id="botaoCad">
        <a href="#" title="Imprimir">Imprimir</a>
</div>

<table id="tabela">
    <tr>
        <th>Nome Usuario</th>
        <th>Nome Projeto</th>
        <th>Produtividade (tempo)</th>
    </tr>
    <?php
    foreach ($this->vRelatorioCol as $relatorio):
    ?>
    <tr>
        <td><?= $relatorio->nomeusuario ?></td>
        <td><?= $relatorio->nomeprojeto ?></td>
        <?php 
        $tempo=$relatorio->tempodedicado;
           $d2="";$h2="";$m2=""; 
           $int1=new DateInterval('P0D');
           $int2=new DateInterval('P0D');
           projetos::trataInterval (&$tempo, &$int2);        
           $int2=projetos::SomaInterval($int1, $int2);       
        ?>
        <td><?= $int2->d." days ".$int2->format('%H').":".$int2->format('%I').":".$int2->format('%S')?></td>     
    </tr>
    <?php
    endforeach;
    ?>
</table>

