<?php echo $this->headLink()->appendStylesheet('/css/telaGrafico.css');
      echo $this->headScript()->appendFile('/js/jquery-1.7.2.js');
      echo $this->headScript()->appendFile('/js/layoutTabela.js');
?>

<div type="button" id="botaoCad">
        <a href="#" title="Imprimir">Imprimir</a>
</div>

<table id="tabela">
    <tr>
        <th>Nome Usuario: </th>
        <th>Data Início: </th>
        <th>Data Fim: </th>
        <th>Papel: </th>
    </tr>
    <?php
    foreach ($this->vUsuarioProjeto as $relatorio):
       ?>
    <tr>
        <td><?= $relatorio->nomeusuario ?></td>
        <td><?= $relatorio->datainiciousuario ?></td>
        <td><?= $relatorio->datafimusuario ?></td>
        <td><?= $relatorio->papel ?></td>
    </tr>
    <?php
    endforeach;
    ?>
</table>